---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in application"

    - name: install apps from homebrew
      homebrew: name={{item}} state=present
      with_items:
          - bash-completion
          - coreutils
          - git
          - rbenv
          - wget
          - pyenv
          - the_silver_searcher
          - brew-cask

    - name: install casks
      homebrew_cask: name={{item}}
      sudo: no
      with_items:
         - atom
         - calibre
         - firefox
         - google-chrome
         - skype
         - pycharm
         - lastpass-universal
         - mou
         - spotify

    - name: install sudo casks
      homebrew_cask: name={{item}}
      sudo: yes
      with_items:
         - google-hangouts
