---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in application"

    - name: install apps from homebrew
      homebrew: name={{item}} state=present
      with_items:
          - bash
          - bash-completion
          - brew-cask
          - coreutils
          - gawk
          - git
          - nmap
          - pyenv
          - rbenv
          - rust
          - ssh-copy-id
          - the_silver_searcher
          - tig
          - tmux
          - wget

    - name: install casks
      homebrew_cask: name={{item}}
      sudo: no
      with_items:
         - atom
         - calibre
         - dropbox
         - firefox
         - flux
         - google-chrome
         - iterm2
         - lastpass-universal
         - mou
         - pycharm
         - skype
         - spotify
         - spectacle
         - vagrant
         - virtualbox
         - vlc
         - xtrafinder

    - name: install sudo casks
      homebrew_cask: name={{item}}
      sudo: yes
      with_items:
         - google-hangouts
