---
- hosts: workstation
  gather_facts: no           
  sudo: no
  vars:
    homebrew_cask_packages_packages:
      - atom
      - calibre
      - firefox
      - google-chrome
      - iterm2
      - java
      - kindle
      - skype
      - vagrant
      - virtualbox
  roles:
    - hnakamur.homebrew-cask-packages

